print('Aluguel de carros')
print('Digite valores a seguir.')
print()
kmPercorridos = float(input('Quantidade de quilômetros percorridos: '))
diasAlugado = int(input('Quantidade de dias alugado: '))
precoAPagar = (60 * diasAlugado) + (0.15 * kmPercorridos)
print()
print('Valor diário: R$60,00')
print('Valor por quilômetro rodado: R$0,15')
print(f'Preço a pagar: R${precoAPagar:.2f}')
