print('Exibição de horas e conversão para segundos')
print('Atribua os valores desejados a seguir.')
print()
dias = int(input('Dias: '))
horas = int(input('Horas: '))
minutos = int(input('Minutos: '))
segundos = int(input('Segundos: '))
segundosTotal = ((dias * 86400) + (horas * 3600) + (minutos * 60) + segundos)
print()
print('Total de segundos:', segundosTotal)
